name: Accessibility Checks

on:
  pull_request:
    branches:
      - main # Change this to your main branch name

jobs:
  accessibility-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.1 # You can change this to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run jsx-a11y checks
        run: npx eslint --ext .ts,.tsx "src/**/*.{ts,tsx}" --plugin jsx-a11y
