name: Lighthouse Accessibility Check

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get PR URL
        id: pr_url
        run: |
          PR_URL="https://$GITHUB_REPOSITORY/pull/$PR_NUMBER"
          echo "PR_URL=$PR_URL" >> $GITHUB_ENV
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: Install dependencies
        run: npm install

      - name: Run Lighthouse
        run: npx lighthouse ${{ env.PR_URL }} --config-path=lighthouse-config.js --output json --output-path=lighthouse-report.json

      - name: Upload Lighthouse Report
        uses: actions/upload-artifact@v2
        with:
          name: lighthouse-report
          path: lighthouse-report.json
